-- Manual deployment position 1 of Monthsary Phase 2: E schema foundation plus D supporter changes.
-- The numeric suffix identifies section ownership; migrations are applied manually in review order.
BEGIN;

ALTER TABLE public.users_bag
  ADD COLUMN IF NOT EXISTS custom_avatar_token integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS custom_deity_token integer NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'users_bag_custom_avatar_token_check'
       AND conrelid = 'public.users_bag'::regclass
  ) THEN
    ALTER TABLE public.users_bag
      ADD CONSTRAINT users_bag_custom_avatar_token_check
      CHECK (custom_avatar_token >= 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'users_bag_custom_deity_token_check'
       AND conrelid = 'public.users_bag'::regclass
  ) THEN
    ALTER TABLE public.users_bag
      ADD CONSTRAINT users_bag_custom_deity_token_check
      CHECK (custom_deity_token >= 0);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.tickets (
    ticket_id text PRIMARY KEY,
    type text NOT NULL CHECK (type IN ('avatar', 'deity')),
    user_id varchar(20) NOT NULL
      REFERENCES public.users(discord_id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'queued'
      CHECK (status IN ('queued', 'in_progress', 'done')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    completed_by varchar(20),
    notes text
);

CREATE TABLE IF NOT EXISTS public.supporter_item_grants (
    grant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id varchar(20) NOT NULL
      REFERENCES public.users(discord_id) ON DELETE CASCADE,
    item_key varchar(32) NOT NULL
      CHECK (item_key IN ('custom_deity_token')),
    quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
    grant_reason varchar(32) NOT NULL,
    grant_ref varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT supporter_item_grants_idempotency_key
      UNIQUE (discord_id, item_key, grant_reason, grant_ref)
);

CREATE INDEX IF NOT EXISTS idx_tickets_status_type_created
  ON public.tickets(status, type, created_at);

ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supporter_item_grants ENABLE ROW LEVEL SECURITY;

COMMIT;
