-- Manual deployment position 4 of Monthsary Phase 2: A character presets.
-- Run 20260803_01_user_presets_preflight.sql first.
-- This migration creates and backfills preset storage; it does not drop legacy columns.
BEGIN;

CREATE TABLE IF NOT EXISTS public.user_presets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id varchar(20) NOT NULL
        REFERENCES public.users(discord_id) ON DELETE CASCADE,
    slot smallint NOT NULL,
    name varchar(32),
    equipped_deity_1_id integer
        REFERENCES public.user_deities(user_deity_id) ON DELETE SET NULL,
    equipped_deity_2_id integer
        REFERENCES public.user_deities(user_deity_id) ON DELETE SET NULL,
    equipped_deity_3_id integer
        REFERENCES public.user_deities(user_deity_id) ON DELETE SET NULL,
    equipped_echo_deity_id integer
        REFERENCES public.user_deities(user_deity_id) ON DELETE SET NULL,
    equipped_armor_id varchar(8)
        REFERENCES public.user_armors(armor_id) ON DELETE SET NULL,
    equipped_weapon_id varchar(8)
        REFERENCES public.user_weapons(weapon_id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT user_presets_slot_check CHECK (slot IN (1, 2)),
    CONSTRAINT user_presets_echo_source_check CHECK (
      equipped_echo_deity_id IS NULL
      OR equipped_echo_deity_id IS NOT DISTINCT FROM equipped_deity_2_id
      OR equipped_echo_deity_id IS NOT DISTINCT FROM equipped_deity_3_id
    ),
    CONSTRAINT user_presets_discord_slot_key UNIQUE (discord_id, slot)
);

CREATE INDEX IF NOT EXISTS idx_user_presets_discord_id
    ON public.user_presets(discord_id);

ALTER TABLE public.user_presets ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.user_character
    ADD COLUMN IF NOT EXISTS active_preset_slot smallint NOT NULL DEFAULT 1;

DO $user_presets_slot_check$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'user_character_active_preset_slot_check'
       AND conrelid = 'public.user_character'::regclass
  ) THEN
    ALTER TABLE public.user_character
      ADD CONSTRAINT user_character_active_preset_slot_check
      CHECK (active_preset_slot IN (1, 2));
  END IF;
END;
$user_presets_slot_check$;

INSERT INTO public.user_presets
  (discord_id, slot, name,
   equipped_deity_1_id, equipped_deity_2_id, equipped_deity_3_id,
   equipped_echo_deity_id, equipped_armor_id, equipped_weapon_id)
SELECT discord_id, 1, 'Main',
       active_deity_id, active_deity_id_2, active_deity_id_3,
       CASE
         WHEN active_echo_deity_id IS NOT NULL
          AND (active_echo_deity_id IS NOT DISTINCT FROM active_deity_id_2
            OR active_echo_deity_id IS NOT DISTINCT FROM active_deity_id_3)
         THEN active_echo_deity_id
         ELSE NULL
       END,
       equipped_armor_id, equipped_weapon_id
  FROM public.user_character
ON CONFLICT (discord_id, slot) DO NOTHING;

INSERT INTO public.user_presets (discord_id, slot, name)
SELECT discord_id, 2, 'Preset 2'
  FROM public.user_character
ON CONFLICT (discord_id, slot) DO NOTHING;

COMMIT;
