-- Manual deployment position 3 of Monthsary Phase 2: boss source and calamity queue.
BEGIN;

ALTER TABLE public.boss_state
  ADD COLUMN IF NOT EXISTS spawn_source varchar(10) NOT NULL DEFAULT 'natural';

CREATE TABLE IF NOT EXISTS public.boss_spawn_queue (
  queue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id varchar(20) NOT NULL,
  boss_name text NOT NULL,
  requested_by varchar(20) NOT NULL,
  status varchar(10) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'spawning', 'spawned', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  claim_started_at timestamptz,
  spawned_at timestamptz,
  cancelled_at timestamptz,
  cancelled_by varchar(20),
  spawn_id uuid
);

CREATE UNIQUE INDEX IF NOT EXISTS boss_spawn_queue_one_live_per_guild
  ON public.boss_spawn_queue (guild_id)
  WHERE status IN ('pending', 'spawning');

ALTER TABLE public.boss_spawn_queue ENABLE ROW LEVEL SECURITY;

COMMIT;
